server:
  servlet:
    context-path: /api/system

# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/management_system?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ytr689493
  main:
    allow-bean-definition-overriding: true

  #上传文件配置
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1024MB

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印日志
    map-underscore-to-camel-case: true  #开启驼峰命名法
  mapper-locations:
    - classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  global-config:
    db-config:
      id-type: auto #全局自增
